name: uni_escom
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.9.0 <4.0.0"


dependencies:
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  flutter:
    sdk: flutter
  google_fonts: ^6.3.3
  provider: ^6.1.5+1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^19.5.0
  firebase_storage: ^13.0.5
  image_picker: ^1.2.1


dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
